import type { Metadata } from "next";
import clsx from "clsx";
import { iranYecanX } from "@/public/fonts"
import "./globals.css";

export const metadata: Metadata = {
  title: "ساعت خواب نوزاد",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={clsx('background-container', iranYecanX.className)}>
        {children}
      </body>
    </html >
  );
}
